name: create and publish docker image

on:
  push:
    branches:
      - "main"


jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/tomekpwsb/docker-django
          tags: |
            type=ref,event=branch
            type=raw,value=latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DJANGO }}

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=docker,dest=/tmp/image.tar

      - name: Load images
        run: |
          docker load --input /tmp/image.tar

      - name: Publish to Github Container Repository
        run: |
          docker image ls -a
          docker push -a ghcr.io/tomekpwsb/docker-django